spring.application.name=urlshortenerservice

server.port=8081


spring.datasource.url=${postgresql://postgres:XaTMRumlcRXLHgGhubTnEhNpnXOxDGdE@postgres.railway.internal:5432/railway}spring.datasource.username=postgres
spring.datasource.username=${postgres}
spring.datasource.password=${XaTMRumlcRXLHgGhubTnEhNpnXOxDGdE}
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.enabled=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# JWT ? minimum 32 characters for HS256
jwt.secret=${JWT_SECRET:mySecretKeyForJWTThatIsAtLeast32CharsLong}
jwt.expiration=86400000 
# 24 hours

# Disable open-in-view
spring.jpa.open-in-view=false


# Redis config

spring.data.redis.url=${redis://default:IgDvIvUNwiPmxqkwVmbEqaQzIvHoqmOY@redis.railway.internal:6379}
spring.cache.type=redis
spring.data.redis.timeout=2000ms

# Kafka config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.ack-mode=manual_immediate
spring.kafka.producer.key-serializer=\
    org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=\
    org.springframework.kafka.support.serializer.JsonSerializer
kafka.enabled=${KAFKA_ENABLED:false}
spring.kafka.listener.missing-topics-fatal=false
